export class Contractors {
  User_pkeyID: Number = 0;
  User_Title: string = '';
  User_FirstName: string = '';
  User_MiddleName: string = '';
  User_LastName: string = '';
  User_CompanyName: string = '';
  User_VendoID: Number = 0;
  User_Sys_Record: Number = 0;
  User_LoginName: string = '';
  User_Password: string = '';
  User_Email: string = '';
  User_Group: Number = 0;
  User_ClientAssignArray: string = '';
  User_Assi_Admin: Number = 0;
  User_Active: Number = 1;
  User_WorkOrder: Number = 0;
  User_Wo_History: Number = 0;
  User_Disc_percentage: string = '';
  User_Tme_Zone: string = '0';
  User_Auto_Assign: Boolean = false;
  User_Leg_FirstName: string = '';
  User_Leg_LastName: string = '';
  User_Leg_CellPhone: string = '';
  User_Leg_Address: string = '';
  User_Leg_Address1: string = '';
  IPL_City: string = '';
  IPL_State: string = '0';
  User_Leg_Notes: Number = 0;
  User_Email_Note: Boolean = false;
  User_Emai_Reminders: Boolean = false;
  User_Email_New_Wo: Boolean = false;
  User_Email_UnAssigned_Wo: Boolean = false;
  User_Email_FollowUp: Boolean = false;
  User_Text_Note: Boolean = false;
  User_Text_Reminders: Boolean = false;
  User_Text_New_Wo: Boolean = false;
  User_Text_UnAssigned_Wo: Boolean = false;
  User_Text_FollowUp: Boolean = false;
  User_Alert_EmailReply: Boolean = false;
  User_Alert_Ready_Office: Boolean = false;
  User_Misc_Contractor_Score: Number = 0;
  User_Misc_Insurance_Expire: string;
  User_Misc_Pruvan_Username: string = '';
  User_Misc_PushKey: string = '';
  User_Misc_StartDate: string = '0';
  User_Misc_Device_Id: string = '';
  User_Misc_ABC: string = '';
  User_Misc_Service_Id: string = '';
  User_IsActive: Boolean = true;
  User_IsDelete: Boolean = false;
  UserID: Number = 0;
  Type: Number = 0;
  User_CellNumber: Number;
  User_Alert_minutes: Number;
  Carrier: Number = 0;
  IPL_Primary_Zip_Code: string = '';
  IPL_County: string = '';
  User_Comments: string = '';
  StrAddressArray: any;
  User_Contractor: Boolean = false;
  User_Cordinator: Boolean = false;
  User_Processor: Boolean = false;
  User_OpenOrderDisCriteria: string = '0';
  User_PastWorkOrder: Boolean = false;
  User_PastOrderDisCriteria: string = '0';
  User_SelectOrderDisCriteria: string = '';
  User_BackgroundCheckProvider: string = '0';
  User_BackgroundCheckId: string = '';
  // new fields
  User_Email_Cancelled: Boolean = false;
  User_Email_New_Message: Boolean = false;
  User_Email_Field_Complete: Boolean = false;
  User_Email_Daily_Digest: Boolean = false;
  User_Text_Cancelled: Boolean = false;
  User_Text_New_Message: Boolean = false;
  User_Text_Field_Complete: Boolean = false;
  User_AssignClient: string = '';
  UserDocumentArray: any;
  AssociatedDevices: any;
  documentx: File;
  Client_PageCalled: Number;
  User_BackgroundDocPath: string = '';
  User_Con_Cat_Id: Number = 0;
  User_Tracking: Boolean;
  User_Tracking_Time: Number = 0;
  //added
  IPL_Address: any;
  User_Printoncheckas: boolean = false;
  User_BusinessID_Social_No: any;
  User_Track_Payment: boolean = false;
  User_Default_Expence_Account_Id: any = 0;
  User_Default_Expence_Account_IdList: any;
  User_Source: number = 1;
}

export class Vendor {
  Acc_Vendor_pkeyId: number = 0;
  User_pkeyID: number = 0;
  Title: any;
  First_Name: any;
  Middle_Name: any;
  Last_Name: any;
  Company_Name: any;
  Address: any;
  City: any;
  StateId: any = 0;
  ZipCode: any;
  Country: any;
  Email: any;
  Phone: any;
  Mobile: any;
  FaxNumber: any;
  Website: any;
  Type: any = 0;
  BusinessID_Social_No: any;
  Track_Payment: boolean = false;
  Default_Expence_Account_Id: any;
  Default_Expence_Account_IdList: any;
  User_Source: number = 1;
  PrintOnCheck: boolean = false;
  MenuID: any;
  UserID: any;
  WhereClause: any;
  IsActive: boolean = true;
  CreatedBy: string = '';
  ModifiedBy: string = '';
}
